REPO_ROOT ?= $(shell git rev-parse --show-toplevel)
-include $(REPO_ROOT)/build.mk

export VERSION=2.11.2
export REV=0

# check version
# https://hub.docker.com/_/caddy
# https://github.com/caddyserver/caddy/releases

push:
