REPO_ROOT ?= $(shell git rev-parse --show-toplevel)
-include $(REPO_ROOT)/build.mk

# https://hub.docker.com/r/gitea/act_runner/tags
# https://gitea.com/gitea/act_runner
export VERSION=0.2.12

push:
print:
