FROM wener/base:edge
MAINTAINER wener

RUN apk add --no-cache asterisk openssl && \
    apk add --no-cache asterisk-{alsa,cdr-mysql,chan-dongle,curl,dahdi,dbg,dev,doc,fax,mobile,odbc,pgsql,sample-config,sounds-en,sounds-moh,speex,srtp,tds}

