REPO_ROOT ?= $(shell git rev-parse --show-toplevel)
-include $(REPO_ROOT)/build.mk

# git describe from wenerme/mihomo develop branch
export VERSION:=1.19.22
# change MIHOMO_REV to bust docker cache when code updates
export MIHOMO_REV:=fb5d1f3dae0317d625df9ea1a8394cc4491b87dc

print:
push:
